#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : libXv
Version  : 1.0.12
Release  : 18
URL      : https://www.x.org/releases/individual/lib/libXv-1.0.12.tar.gz
Source0  : https://www.x.org/releases/individual/lib/libXv-1.0.12.tar.gz
Source1  : https://www.x.org/releases/individual/lib/libXv-1.0.12.tar.gz.sig
Summary  : The Xv Library
Group    : Development/Tools
License  : HPND
Requires: libXv-lib = %{version}-%{release}
Requires: libXv-license = %{version}-%{release}
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkg-config
BuildRequires : pkgconfig(32videoproto)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xext)
BuildRequires : pkgconfig(32xextproto)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(videoproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xorg-macros)

%description
libXv - library for the X Video (Xv) extension to the X Window System
---------------------------------------------------------------------

%package dev
Summary: dev components for the libXv package.
Group: Development
Requires: libXv-lib = %{version}-%{release}
Provides: libXv-devel = %{version}-%{release}
Requires: libXv = %{version}-%{release}

%description dev
dev components for the libXv package.


%package dev32
Summary: dev32 components for the libXv package.
Group: Default
Requires: libXv-lib32 = %{version}-%{release}
Requires: libXv-dev = %{version}-%{release}

%description dev32
dev32 components for the libXv package.


%package lib
Summary: lib components for the libXv package.
Group: Libraries
Requires: libXv-license = %{version}-%{release}

%description lib
lib components for the libXv package.


%package lib32
Summary: lib32 components for the libXv package.
Group: Default
Requires: libXv-license = %{version}-%{release}

%description lib32
lib32 components for the libXv package.


%package license
Summary: license components for the libXv package.
Group: Default

%description license
license components for the libXv package.


%prep
%setup -q -n libXv-1.0.12
cd %{_builddir}/libXv-1.0.12
pushd ..
cp -a libXv-1.0.12 build32
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1670224198
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32 -mstackrealign"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32 -mstackrealign"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../build32;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1670224198
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libXv
cp %{_builddir}/libXv-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libXv/d1845ff7fcb2cdc1f5713dd18140e89de2ab0204
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/Xvlib.h
/usr/lib64/libXv.so
/usr/lib64/pkgconfig/xv.pc
/usr/share/man/man3/Xv.3
/usr/share/man/man3/XvCreateImage.3
/usr/share/man/man3/XvFreeAdaptorInfo.3
/usr/share/man/man3/XvFreeEncodingInfo.3
/usr/share/man/man3/XvGetPortAttribute.3
/usr/share/man/man3/XvGetStill.3
/usr/share/man/man3/XvGetVideo.3
/usr/share/man/man3/XvGrabPort.3
/usr/share/man/man3/XvListImageFormats.3
/usr/share/man/man3/XvPortNotify.3
/usr/share/man/man3/XvPutImage.3
/usr/share/man/man3/XvPutStill.3
/usr/share/man/man3/XvPutVideo.3
/usr/share/man/man3/XvQueryAdaptors.3
/usr/share/man/man3/XvQueryBestSize.3
/usr/share/man/man3/XvQueryEncodings.3
/usr/share/man/man3/XvQueryExtension.3
/usr/share/man/man3/XvQueryPortAttributes.3
/usr/share/man/man3/XvSelectPortNotify.3
/usr/share/man/man3/XvSelectVideoNotify.3
/usr/share/man/man3/XvSetPortAttribute.3
/usr/share/man/man3/XvShmCreateImage.3
/usr/share/man/man3/XvShmPutImage.3
/usr/share/man/man3/XvStopVideo.3
/usr/share/man/man3/XvUngrabPort.3
/usr/share/man/man3/XvVideoNotify.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libXv.so
/usr/lib32/pkgconfig/32xv.pc
/usr/lib32/pkgconfig/xv.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXv.so.1
/usr/lib64/libXv.so.1.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libXv.so.1
/usr/lib32/libXv.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libXv/d1845ff7fcb2cdc1f5713dd18140e89de2ab0204
