#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v21
# autospec commit: 5424026
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : libXv
Version  : 1.0.13
Release  : 19
URL      : https://www.x.org/releases/individual/lib/libXv-1.0.13.tar.gz
Source0  : https://www.x.org/releases/individual/lib/libXv-1.0.13.tar.gz
Source1  : https://www.x.org/releases/individual/lib/libXv-1.0.13.tar.gz.sig
Source2  : CFDF148828C642A7.pkey
Summary  : The Xv Library
Group    : Development/Tools
License  : HPND
Requires: libXv-lib = %{version}-%{release}
Requires: libXv-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : gnupg
BuildRequires : pkg-config
BuildRequires : pkgconfig(32videoproto)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xext)
BuildRequires : pkgconfig(32xextproto)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(videoproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xorg-macros)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libXv - library for the X Video (Xv) extension to the X Window System
---------------------------------------------------------------------

%package dev
Summary: dev components for the libXv package.
Group: Development
Requires: libXv-lib = %{version}-%{release}
Provides: libXv-devel = %{version}-%{release}
Requires: libXv = %{version}-%{release}

%description dev
dev components for the libXv package.


%package dev32
Summary: dev32 components for the libXv package.
Group: Default
Requires: libXv-lib32 = %{version}-%{release}
Requires: libXv-dev = %{version}-%{release}

%description dev32
dev32 components for the libXv package.


%package lib
Summary: lib components for the libXv package.
Group: Libraries
Requires: libXv-license = %{version}-%{release}

%description lib
lib components for the libXv package.


%package lib32
Summary: lib32 components for the libXv package.
Group: Default
Requires: libXv-license = %{version}-%{release}

%description lib32
lib32 components for the libXv package.


%package license
Summary: license components for the libXv package.
Group: Default

%description license
license components for the libXv package.


%prep
mkdir .gnupg
chmod 700 .gnupg
gpg --homedir .gnupg --import %{SOURCE2}
gpg --homedir .gnupg --status-fd 1 --verify %{SOURCE1} %{SOURCE0} > gpg.status
grep -E '^\[GNUPG:\] (GOODSIG|EXPKEYSIG) CFDF148828C642A7' gpg.status
%setup -q -n libXv-1.0.13
cd %{_builddir}/libXv-1.0.13
pushd ..
cp -a libXv-1.0.13 build32
popd
pushd ..
cp -a libXv-1.0.13 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1735598082
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
ASFLAGS="${CLEAR_INTERMEDIATE_ASFLAGS}${CLEAR_INTERMEDIATE_ASFLAGS:+ }--32"
CFLAGS="${CLEAR_INTERMEDIATE_CFLAGS}${CLEAR_INTERMEDIATE_CFLAGS:+ }-m32 -mstackrealign"
CXXFLAGS="${CLEAR_INTERMEDIATE_CXXFLAGS}${CLEAR_INTERMEDIATE_CXXFLAGS:+ }-m32 -mstackrealign"
LDFLAGS="${CLEAR_INTERMEDIATE_LDFLAGS}${CLEAR_INTERMEDIATE_LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../build32;
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -flto=auto -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1735598082
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libXv
cp %{_builddir}/libXv-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libXv/d1845ff7fcb2cdc1f5713dd18140e89de2ab0204 || :
export GOAMD64=v2
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/extensions/Xvlib.h
/usr/lib64/libXv.so
/usr/lib64/pkgconfig/xv.pc
/usr/share/man/man3/Xv.3
/usr/share/man/man3/XvCreateImage.3
/usr/share/man/man3/XvFreeAdaptorInfo.3
/usr/share/man/man3/XvFreeEncodingInfo.3
/usr/share/man/man3/XvGetPortAttribute.3
/usr/share/man/man3/XvGetStill.3
/usr/share/man/man3/XvGetVideo.3
/usr/share/man/man3/XvGrabPort.3
/usr/share/man/man3/XvListImageFormats.3
/usr/share/man/man3/XvPortNotify.3
/usr/share/man/man3/XvPutImage.3
/usr/share/man/man3/XvPutStill.3
/usr/share/man/man3/XvPutVideo.3
/usr/share/man/man3/XvQueryAdaptors.3
/usr/share/man/man3/XvQueryBestSize.3
/usr/share/man/man3/XvQueryEncodings.3
/usr/share/man/man3/XvQueryExtension.3
/usr/share/man/man3/XvQueryPortAttributes.3
/usr/share/man/man3/XvSelectPortNotify.3
/usr/share/man/man3/XvSelectVideoNotify.3
/usr/share/man/man3/XvSetPortAttribute.3
/usr/share/man/man3/XvShmCreateImage.3
/usr/share/man/man3/XvShmPutImage.3
/usr/share/man/man3/XvStopVideo.3
/usr/share/man/man3/XvUngrabPort.3
/usr/share/man/man3/XvVideoNotify.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libXv.so
/usr/lib32/pkgconfig/32xv.pc
/usr/lib32/pkgconfig/xv.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libXv.so.1.0.0
/usr/lib64/libXv.so.1
/usr/lib64/libXv.so.1.0.0

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libXv.so.1
/usr/lib32/libXv.so.1.0.0

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libXv/d1845ff7fcb2cdc1f5713dd18140e89de2ab0204
